"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { build, normalize } = require("./build-stories.cjs");
const root = path.join(__dirname,"..");
const input = JSON.parse(fs.readFileSync(path.join(root,"story/posts.json"),"utf8"));
const run = posts => build(root,{posts,write:false});
const original = run(input);
assert.equal(original.posts.length,input.length);
for(const p of original.posts) {
  const html = original.output.get("story/"+p.url);
  assert.ok(html.includes("<h1>"+p.title+"</h1>"));
  assert.ok(html.includes('<div class="post-body"><p>'));
  assert.ok(!html.includes('fetch("posts.json"'));
  for(const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) JSON.parse(m[1]);
  for(const file of ["sitemap.xml","feed.xml","llms.txt","story/index.html"]) assert.ok(original.output.get(file).includes(p.url));
}
const edit = structuredClone(input);
edit[0].title = "수정 동기화 시험 제목";
edit[0].body = "수정 동기화 시험 본문\n\n## 시험 소제목\n\n추가 설명";
edit[0].summary = "수정 동기화 시험 요약";
edit[0].description = "수정 동기화 시험 설명";
edit[0].updated = "2026-09-10";
edit[0].faq[0] = {q:"바뀐 질문?",a:"바뀐 답"};
const edited = run(edit);
const html = edited.output.get("story/"+edit[0].url);
for(const value of ["수정 동기화 시험 제목","수정 동기화 시험 본문","수정 동기화 시험 설명","바뀐 질문?","바뀐 답","2026-09-10"]) assert.ok(html.includes(value));
assert.ok(!html.includes(input[0].body.split("\n")[0]));
assert.ok(edited.output.get("index.html").includes(edit[0].summary));
assert.ok(edited.output.get("sitemap.xml").includes("<lastmod>2026-09-10</lastmod>"));
assert.ok(edited.output.get("feed.xml").includes(edit[0].title));
assert.ok(edited.output.get("llms.txt").includes(edit[0].summary));
const newPost = {...edit[0],id:"new-test-id",url:undefined,title:"추가 시험 글",date:"2026-09-10"};
const added = run([...input,newPost]);
const newURL = added.posts.find(p=>p.id==="new-test-id").url;
assert.match(newURL,/^post-[a-f0-9]+\.html$/);
assert.ok(added.output.has("story/"+newURL));
assert.ok(added.output.get("index.html").includes(newURL));
assert.equal(run([...input,newPost]).posts.find(p=>p.id==="new-test-id").url,newURL);
const removed = run(input.slice(1));
assert.ok(!removed.output.has("story/"+input[0].url));
for(const file of ["sitemap.xml","feed.xml","llms.txt","index.html","story/index.html"]) assert.ok(!removed.output.get(file).includes(input[0].url));
const empty=run([]);
assert.ok(empty.output.get("story/index.html").includes("아직 발행된"));
assert.ok(!empty.output.get("sitemap.xml").includes(".html</loc><lastmod>"));
assert.throws(()=>normalize([...input,input[0]]),/Duplicate/);
assert.throws(()=>normalize([{...input[0],url:"../index.html"}]),/Unsafe/);
assert.throws(()=>normalize([{...input[0],url:"index.html"}]),/Unsafe/);
assert.throws(()=>normalize([{...input[0],date:"2026-02-30"}]),/Invalid/);
assert.throws(()=>normalize([{...input[0],sources:[{title:"bad",url:"javascript:alert(1)"}]}]),/Invalid/);
const injection=run([{...input[0],title:'</script><script>alert("test")</script>',body:"<img src=x onerror=alert(1)>"}]).output.get("story/"+input[0].url);
assert.ok(!injection.includes('<script>alert'));
assert.ok(injection.includes("&lt;img"));
for(const m of injection.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) JSON.parse(m[1]);
const preview=build(root,{write:false,preview:true});
assert.ok(preview.output.get("story/"+input[0].url).includes('name="robots" content="noindex,nofollow"'));
for(const file of original.output.keys()) assert.ok(!file.startsWith("scripts/")&&!file.startsWith(".git/")&&!file.startsWith(".agents/"));
console.log("PASS: existing 5, edit, add, delete, empty, stable URL, duplicate/path/date rejection, XSS escaping, preview noindex, private-file exclusion");
